# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure("2") do |vagrant|
  hostname = "k253m1"

  vagrant.vm.define hostname, primary: true do |machine|
    machine.vm.box = "sT0wn/kalilinux_arm64"
    machine.vm.box_version = "2025.3"
    machine.vm.hostname = hostname

    machine.vm.provider "utm" do |u|
      u.name = hostname
      u.cpus = 8
      u.memory = 8192
      u.notes = "Vagrant: for testing and emulating services"
      u.directory_share_mode = "virtFS"
    end

  end
end
