---
- name: Manage Kali Linux VM in UTM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # Define VM Configuration Variables
    ansible_user_dir: "/Users/arx/virt/"
    download_dir: "{{ ansible_user_dir }}/isos/"
    vm_name: "kali-linux-arm64"
    iso_filename: "kali-linux-2025.3-installer-arm64.iso"
    vm_memory: 8192
    vm_cpus: 8
    disk_size_gb: 64

  tasks:
    - name: Check if VM already exists (via status command)
      ansible.builtin.command: "utmctl list {{ vm_name }}"
      register: vm_exists_check
      ignore_errors: true
      changed_when: false

    - name: Create and configure VM if it does not exist
      when: vm_exists_check.rc != 0
      block:
        - name: Create base VM structure
          ansible.builtin.command:
            cmd: >
              utmctl create
              --name "{{ vm_name }}"
              --architecture aarch64
              --cores {{ vm_cpus }}
              --memory {{ vm_memory }}
          register: create_output
          changed_when: create_output.rc == 0 
